#!/bin/sh

set -e
set -u

if [ $# -ne 0 ]; then
    echo >&2 "Usage: $0"
    exit 1
fi

. ./package_vars.sh

# https://bugs.launchpad.net/launchpad/+bug/1699763
sed -i -e '/buildinfo/d' "$CHANGES_FILE"

debsign "$CHANGES_FILE"
dput "ppa:$(whoami)/${PACKAGE_NAME}" "${CHANGES_FILE}"
